2021-02-13T20:25:38.244412+00:00 app[worker.1]: Traceback (most recent call last):
2021-02-13T20:25:38.244478+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 343, in _run_event
2021-02-13T20:25:38.244479+00:00 app[worker.1]: await coro(*args, **kwargs)
2021-02-13T20:25:38.244509+00:00 app[worker.1]: File "/app/bot/cogs/reaction_handler.py", line 18, in on_raw_reaction_add
2021-02-13T20:25:38.244510+00:00 app[worker.1]: await urban_handler(self.bot, payload)
2021-02-13T20:25:38.244547+00:00 app[worker.1]: File "/app/bot/cogs/services.py", line 157, in urban_handler
2021-02-13T20:25:38.244548+00:00 app[worker.1]: and message.embeds[0].title.startswith("Page")
2021-02-13T20:25:38.244599+00:00 app[worker.1]: AttributeError: '_EmptyEmbed' object has no attribute 'startswith'
2021-02-13T21:12:33.000000+00:00 app[api]: Build started by user thederevin@gmail.com
2021-02-13T21:13:03.908619+00:00 app[api]: Release v249 created by user thederevin@gmail.com
2021-02-13T21:13:03.908619+00:00 app[api]: Deploy 0249cc2b by user thederevin@gmail.com
2021-02-13T21:13:05.292101+00:00 heroku[worker.1]: Restarting
2021-02-13T21:13:05.296023+00:00 heroku[worker.1]: State changed from up to starting
2021-02-13T21:13:06.269508+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2021-02-13T21:13:06.557098+00:00 heroku[worker.1]: Process exited with status 0
2021-02-13T21:13:10.338611+00:00 heroku[worker.1]: Starting process with command `python bot/main.py`
2021-02-13T21:13:11.020498+00:00 heroku[worker.1]: State changed from starting to up
2021-02-13T21:13:13.657587+00:00 app[worker.1]: prod
2021-02-13T21:13:17.000000+00:00 app[api]: Build succeeded
2021-02-13T21:13:17.041283+00:00 app[worker.1]: expected create exception: constraint "usr_fk0" for relation "usr" already exists
2021-02-13T21:19:41.000000+00:00 app[api]: Build started by user thederevin@gmail.com
2021-02-13T21:20:13.663235+00:00 app[api]: Release v250 created by user thederevin@gmail.com
2021-02-13T21:20:13.663235+00:00 app[api]: Deploy 5deefe56 by user thederevin@gmail.com
2021-02-13T21:20:14.924185+00:00 heroku[worker.1]: Restarting
2021-02-13T21:20:14.956070+00:00 heroku[worker.1]: State changed from up to starting
2021-02-13T21:20:15.982266+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2021-02-13T21:20:16.315566+00:00 heroku[worker.1]: Process exited with status 0
2021-02-13T21:20:19.668133+00:00 heroku[worker.1]: Starting process with command `python bot/main.py`
2021-02-13T21:20:20.435723+00:00 heroku[worker.1]: State changed from starting to up
2021-02-13T21:20:23.053799+00:00 app[worker.1]: prod
2021-02-13T21:20:25.734206+00:00 app[worker.1]: expected create exception: constraint "usr_fk0" for relation "usr" already exists
2021-02-13T21:20:27.000000+00:00 app[api]: Build succeeded
2021-02-13T21:20:52.000000+00:00 app[api]: Build started by user thederevin@gmail.com
2021-02-13T21:21:23.324109+00:00 app[api]: Release v251 created by user thederevin@gmail.com
2021-02-13T21:21:23.324109+00:00 app[api]: Deploy cfcbb04a by user thederevin@gmail.com
2021-02-13T21:21:24.616239+00:00 heroku[worker.1]: Restarting
2021-02-13T21:21:24.655861+00:00 heroku[worker.1]: State changed from up to starting
2021-02-13T21:21:25.706725+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2021-02-13T21:21:29.263414+00:00 heroku[worker.1]: Starting process with command `python bot/main.py`
2021-02-13T21:21:29.886860+00:00 heroku[worker.1]: State changed from starting to up
2021-02-13T21:21:31.698739+00:00 app[worker.1]: prod
2021-02-13T21:21:33.458488+00:00 app[worker.1]: expected create exception: constraint "usr_fk0" for relation "usr" already exists
2021-02-13T21:21:37.000000+00:00 app[api]: Build succeeded
2021-02-13T21:21:55.859617+00:00 heroku[worker.1]: Error R12 (Exit timeout) -> At least one process failed to exit within 30 seconds of SIGTERM
2021-02-13T21:21:55.863746+00:00 heroku[worker.1]: Stopping remaining processes with SIGKILL
2021-02-13T21:21:55.942559+00:00 heroku[worker.1]: Process exited with status 137
2021-02-13T21:25:57.000000+00:00 app[api]: Build started by user thederevin@gmail.com
2021-02-13T21:26:30.627031+00:00 app[api]: Deploy 2ead4d43 by user thederevin@gmail.com
2021-02-13T21:26:30.627031+00:00 app[api]: Release v252 created by user thederevin@gmail.com
2021-02-13T21:26:32.167154+00:00 heroku[worker.1]: Restarting
2021-02-13T21:26:32.189837+00:00 heroku[worker.1]: State changed from up to starting
2021-02-13T21:26:33.178143+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2021-02-13T21:26:33.443704+00:00 heroku[worker.1]: Process exited with status 0
2021-02-13T21:26:36.821123+00:00 heroku[worker.1]: Starting process with command `python bot/main.py`
2021-02-13T21:26:37.452529+00:00 heroku[worker.1]: State changed from starting to up
2021-02-13T21:26:39.488670+00:00 app[worker.1]: prod
2021-02-13T21:26:41.699502+00:00 app[worker.1]: expected create exception: constraint "usr_fk0" for relation "usr" already exists
2021-02-13T21:26:45.000000+00:00 app[api]: Build succeeded
2021-02-13T21:28:16.000000+00:00 app[api]: Build started by user thederevin@gmail.com
2021-02-13T21:28:48.215292+00:00 app[api]: Deploy 274f57d4 by user thederevin@gmail.com
2021-02-13T21:28:48.215292+00:00 app[api]: Release v253 created by user thederevin@gmail.com
2021-02-13T21:28:49.723526+00:00 heroku[worker.1]: Restarting
2021-02-13T21:28:49.744620+00:00 heroku[worker.1]: State changed from up to starting
2021-02-13T21:28:50.569763+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2021-02-13T21:28:50.813580+00:00 heroku[worker.1]: Process exited with status 0
2021-02-13T21:28:55.462074+00:00 heroku[worker.1]: Starting process with command `python bot/main.py`
2021-02-13T21:28:56.113341+00:00 heroku[worker.1]: State changed from starting to up
2021-02-13T21:28:58.164414+00:00 app[worker.1]: prod
2021-02-13T21:29:00.121944+00:00 app[worker.1]: expected create exception: constraint "usr_fk0" for relation "usr" already exists
2021-02-13T21:29:02.000000+00:00 app[api]: Build succeeded
2021-02-13T21:30:37.000000+00:00 app[api]: Build started by user thederevin@gmail.com
2021-02-13T21:31:11.662677+00:00 app[api]: Release v254 created by user thederevin@gmail.com
2021-02-13T21:31:11.662677+00:00 app[api]: Deploy 45571664 by user thederevin@gmail.com
2021-02-13T21:31:12.965626+00:00 heroku[worker.1]: Restarting
2021-02-13T21:31:12.979562+00:00 heroku[worker.1]: State changed from up to starting
2021-02-13T21:31:14.219619+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2021-02-13T21:31:14.458986+00:00 heroku[worker.1]: Process exited with status 0
2021-02-13T21:31:17.997543+00:00 heroku[worker.1]: Starting process with command `python bot/main.py`
2021-02-13T21:31:18.583058+00:00 heroku[worker.1]: State changed from starting to up
2021-02-13T21:31:21.198443+00:00 app[worker.1]: prod
2021-02-13T21:31:23.807358+00:00 app[worker.1]: expected create exception: constraint "usr_fk0" for relation "usr" already exists
2021-02-13T21:31:25.000000+00:00 app[api]: Build succeeded
2021-02-13T21:36:25.000000+00:00 app[api]: Build started by user thederevin@gmail.com
2021-02-13T21:36:56.148342+00:00 app[api]: Deploy 65ceadda by user thederevin@gmail.com
2021-02-13T21:36:56.148342+00:00 app[api]: Release v255 created by user thederevin@gmail.com
2021-02-13T21:36:57.343323+00:00 heroku[worker.1]: Restarting
2021-02-13T21:36:57.379080+00:00 heroku[worker.1]: State changed from up to starting
2021-02-13T21:36:58.286617+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2021-02-13T21:36:58.548312+00:00 heroku[worker.1]: Process exited with status 0
2021-02-13T21:37:02.132802+00:00 heroku[worker.1]: Starting process with command `python bot/main.py`
2021-02-13T21:37:02.844732+00:00 heroku[worker.1]: State changed from starting to up
2021-02-13T21:37:05.123935+00:00 app[worker.1]: prod
2021-02-13T21:37:07.562169+00:00 app[worker.1]: expected create exception: constraint "usr_fk0" for relation "usr" already exists
2021-02-13T21:37:10.000000+00:00 app[api]: Build succeeded
2021-02-13T21:37:54.920632+00:00 app[worker.1]: Adding user 395328770883584012 with guild 315247766739615745 to db.
2021-02-14T05:38:06.418260+00:00 app[worker.1]: Unhandled exception in internal background task 'kick_inactives'.
2021-02-14T05:38:06.430373+00:00 app[worker.1]: Traceback (most recent call last):
2021-02-14T05:38:06.430433+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
2021-02-14T05:38:06.430434+00:00 app[worker.1]: await self.coro(*args, **kwargs)
2021-02-14T05:38:06.430464+00:00 app[worker.1]: File "/app/bot/cogs/rules.py", line 270, in kick_inactives
2021-02-14T05:38:06.430465+00:00 app[worker.1]: await member.kick()
2021-02-14T05:38:06.430497+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/discord/member.py", line 524, in kick
2021-02-14T05:38:06.430498+00:00 app[worker.1]: await self.guild.kick(self, reason=reason)
2021-02-14T05:38:06.430524+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/discord/guild.py", line 1886, in kick
2021-02-14T05:38:06.430524+00:00 app[worker.1]: await self._state.http.kick(user.id, self.id, reason=reason)
2021-02-14T05:38:06.430557+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/discord/http.py", line 241, in request
2021-02-14T05:38:06.430558+00:00 app[worker.1]: raise Forbidden(r, data)
2021-02-14T05:38:06.430611+00:00 app[worker.1]: discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
2021-02-14T11:58:11.000000+00:00 app[api]: Build started by user thederevin@gmail.com
2021-02-14T11:59:03.562274+00:00 app[api]: Release v256 created by user thederevin@gmail.com
2021-02-14T11:59:03.562274+00:00 app[api]: Deploy f25707ef by user thederevin@gmail.com
2021-02-14T11:59:06.371029+00:00 heroku[worker.1]: Restarting
2021-02-14T11:59:06.375700+00:00 heroku[worker.1]: State changed from up to starting
2021-02-14T11:59:07.888980+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2021-02-14T11:59:08.036631+00:00 app[worker.1]: Task exception was never retrieved
2021-02-14T11:59:08.036642+00:00 app[worker.1]: future: <Task finished coro=<Loop._loop() done, defined at /app/.heroku/python/lib/python3.6/site-packages/discord/ext/tasks/__init__.py:88> exception=Forbidden('403 Forbidden (error code: 50013): Missing Permissions',)>
2021-02-14T11:59:08.036642+00:00 app[worker.1]: Traceback (most recent call last):
2021-02-14T11:59:08.036643+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/tasks/__init__.py", line 125, in _loop
2021-02-14T11:59:08.036645+00:00 app[worker.1]: raise exc
2021-02-14T11:59:08.036645+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
2021-02-14T11:59:08.036646+00:00 app[worker.1]: await self.coro(*args, **kwargs)
2021-02-14T11:59:08.036647+00:00 app[worker.1]: File "/app/bot/cogs/rules.py", line 270, in kick_inactives
2021-02-14T11:59:08.036647+00:00 app[worker.1]: await member.kick()
2021-02-14T11:59:08.036648+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/discord/member.py", line 524, in kick
2021-02-14T11:59:08.036649+00:00 app[worker.1]: await self.guild.kick(self, reason=reason)
2021-02-14T11:59:08.036649+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/discord/guild.py", line 1886, in kick
2021-02-14T11:59:08.036650+00:00 app[worker.1]: await self._state.http.kick(user.id, self.id, reason=reason)
2021-02-14T11:59:08.036650+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/discord/http.py", line 241, in request
2021-02-14T11:59:08.036651+00:00 app[worker.1]: raise Forbidden(r, data)
2021-02-14T11:59:08.036656+00:00 app[worker.1]: discord.errors.Forbidden: 403 Forbidden (error code: 50013): Missing Permissions
2021-02-14T11:59:08.229028+00:00 heroku[worker.1]: Process exited with status 0
2021-02-14T11:59:11.069676+00:00 heroku[worker.1]: Starting process with command `python bot/main.py`
2021-02-14T11:59:11.710880+00:00 heroku[worker.1]: State changed from starting to up
2021-02-14T11:59:14.366147+00:00 app[worker.1]: prod
2021-02-14T11:59:17.000000+00:00 app[api]: Build succeeded
2021-02-14T11:59:17.199620+00:00 app[worker.1]: expected create exception: constraint "usr_fk0" for relation "usr" already exists
2021-02-14T16:40:16.030206+00:00 app[worker.1]: Ignoring exception in on_raw_message_edit
2021-02-14T16:40:16.070078+00:00 app[worker.1]: Traceback (most recent call last):
2021-02-14T16:40:16.070089+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/discord/client.py", line 343, in _run_event
2021-02-14T16:40:16.070090+00:00 app[worker.1]: await coro(*args, **kwargs)
2021-02-14T16:40:16.070092+00:00 app[worker.1]: File "/app/bot/cogs/logs.py", line 33, in on_raw_message_edit
2021-02-14T16:40:16.070092+00:00 app[worker.1]: await logs.send(embed=embed)
2021-02-14T16:40:16.070117+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/discord/abc.py", line 937, in send
2021-02-14T16:40:16.070118+00:00 app[worker.1]: message_reference=reference)
2021-02-14T16:40:16.070120+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/discord/http.py", line 247, in request
2021-02-14T16:40:16.070120+00:00 app[worker.1]: raise HTTPException(r, data)
2021-02-14T16:40:16.070155+00:00 app[worker.1]: discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
2021-02-14T16:40:16.070156+00:00 app[worker.1]: In embed.fields.0.value: This field is required
2021-02-14T20:25:10.000000+00:00 app[api]: Build started by user thederevin@gmail.com
2021-02-14T20:25:42.422707+00:00 app[api]: Release v257 created by user thederevin@gmail.com
2021-02-14T20:25:42.422707+00:00 app[api]: Deploy ad4beb7a by user thederevin@gmail.com
2021-02-14T20:25:43.868554+00:00 heroku[worker.1]: Restarting
2021-02-14T20:25:43.879259+00:00 heroku[worker.1]: State changed from up to starting
2021-02-14T20:25:44.688979+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2021-02-14T20:25:45.003350+00:00 heroku[worker.1]: Process exited with status 0
2021-02-14T20:25:48.274146+00:00 heroku[worker.1]: Starting process with command `python bot/main.py`
2021-02-14T20:25:48.895595+00:00 heroku[worker.1]: State changed from starting to up
2021-02-14T20:25:50.851611+00:00 app[worker.1]: prod
2021-02-14T20:25:54.039184+00:00 app[worker.1]: expected create exception: constraint "usr_fk0" for relation "usr" already exists
2021-02-14T20:25:56.000000+00:00 app[api]: Build succeeded
2021-02-15T17:52:43.000000+00:00 app[api]: Build started by user thederevin@gmail.com
2021-02-15T17:53:15.934454+00:00 app[api]: Release v258 created by user thederevin@gmail.com
2021-02-15T17:53:15.934454+00:00 app[api]: Deploy 499e9e9d by user thederevin@gmail.com
2021-02-15T17:53:17.004345+00:00 heroku[worker.1]: Restarting
2021-02-15T17:53:17.006635+00:00 heroku[worker.1]: State changed from up to starting
2021-02-15T17:53:17.905278+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2021-02-15T17:53:18.249115+00:00 heroku[worker.1]: Process exited with status 0
2021-02-15T17:53:22.788768+00:00 heroku[worker.1]: Starting process with command `python bot/main.py`
2021-02-15T17:53:23.432606+00:00 heroku[worker.1]: State changed from starting to up
2021-02-15T17:53:26.708347+00:00 app[worker.1]: prod
2021-02-15T17:53:29.000000+00:00 app[api]: Build succeeded
2021-02-15T17:53:31.002435+00:00 app[worker.1]: expected create exception: constraint "usr_fk0" for relation "usr" already exists
2021-02-16T18:54:15.435464+00:00 heroku[worker.1]: Cycling
2021-02-16T18:54:15.437416+00:00 heroku[worker.1]: State changed from up to starting
2021-02-16T18:54:16.594541+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2021-02-16T18:54:17.069458+00:00 heroku[worker.1]: Process exited with status 0
2021-02-16T18:54:19.866142+00:00 heroku[worker.1]: Starting process with command `python bot/main.py`
2021-02-16T18:54:20.478009+00:00 heroku[worker.1]: State changed from starting to up
2021-02-16T18:54:22.197432+00:00 app[worker.1]: prod
2021-02-16T18:54:25.097331+00:00 app[worker.1]: expected create exception: constraint "usr_fk0" for relation "usr" already exists
2021-02-17T19:18:38.048852+00:00 heroku[worker.1]: Cycling
2021-02-17T19:18:38.050989+00:00 heroku[worker.1]: State changed from up to starting
2021-02-17T19:18:39.354064+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2021-02-17T19:18:39.830084+00:00 heroku[worker.1]: Process exited with status 0
2021-02-17T19:18:44.049498+00:00 heroku[worker.1]: Starting process with command `python bot/main.py`
2021-02-17T19:18:44.714663+00:00 heroku[worker.1]: State changed from starting to up
2021-02-17T19:18:47.301563+00:00 app[worker.1]: prod
2021-02-17T19:18:51.211439+00:00 app[worker.1]: expected create exception: constraint "usr_fk0" for relation "usr" already exists
2021-02-17T21:46:18.714682+00:00 app[worker.1]: ['tickets', 'log'] has no number
2021-02-18T19:58:01.057175+00:00 heroku[worker.1]: Cycling
2021-02-18T19:58:01.059023+00:00 heroku[worker.1]: State changed from up to starting
2021-02-18T19:58:02.054490+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2021-02-18T19:58:02.407103+00:00 heroku[worker.1]: Process exited with status 0
2021-02-18T19:58:06.011716+00:00 heroku[worker.1]: Starting process with command `python bot/main.py`
2021-02-18T19:58:06.640009+00:00 heroku[worker.1]: State changed from starting to up
2021-02-18T19:58:08.868070+00:00 app[worker.1]: prod
2021-02-18T19:58:12.204364+00:00 app[worker.1]: expected create exception: constraint "usr_fk0" for relation "usr" already exists
2021-02-19T18:25:47.000000+00:00 app[api]: Build started by user thederevin@gmail.com
2021-02-19T18:26:19.162997+00:00 app[api]: Deploy 388d38df by user thederevin@gmail.com
2021-02-19T18:26:19.162997+00:00 app[api]: Release v259 created by user thederevin@gmail.com
2021-02-19T18:26:20.249080+00:00 heroku[worker.1]: Restarting
2021-02-19T18:26:20.255650+00:00 heroku[worker.1]: State changed from up to starting
2021-02-19T18:26:21.189063+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2021-02-19T18:26:21.442939+00:00 heroku[worker.1]: Process exited with status 0
2021-02-19T18:26:24.842639+00:00 heroku[worker.1]: Starting process with command `python bot/main.py`
2021-02-19T18:26:25.513157+00:00 heroku[worker.1]: State changed from starting to up
2021-02-19T18:26:28.648177+00:00 app[worker.1]: prod
2021-02-19T18:26:32.000000+00:00 app[api]: Build succeeded
2021-02-19T18:26:32.212919+00:00 app[worker.1]: expected create exception: constraint "usr_fk0" for relation "usr" already exists
2021-02-19T18:28:02.000000+00:00 app[api]: Build started by user thederevin@gmail.com
2021-02-19T18:28:33.281783+00:00 app[api]: Deploy fac3eb34 by user thederevin@gmail.com
2021-02-19T18:28:33.281783+00:00 app[api]: Release v260 created by user thederevin@gmail.com
2021-02-19T18:28:35.725998+00:00 heroku[worker.1]: Restarting
2021-02-19T18:28:35.745563+00:00 heroku[worker.1]: State changed from up to starting
2021-02-19T18:28:36.722717+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2021-02-19T18:28:36.994568+00:00 heroku[worker.1]: Process exited with status 0
2021-02-19T18:28:40.163315+00:00 heroku[worker.1]: Starting process with command `python bot/main.py`
2021-02-19T18:28:40.772339+00:00 heroku[worker.1]: State changed from starting to up
2021-02-19T18:28:42.722246+00:00 app[worker.1]: prod
2021-02-19T18:28:45.006074+00:00 app[worker.1]: expected create exception: constraint "usr_fk0" for relation "usr" already exists
2021-02-19T18:28:47.000000+00:00 app[api]: Build succeeded
2021-02-20T18:55:09.721389+00:00 heroku[worker.1]: Cycling
2021-02-20T18:55:09.723501+00:00 heroku[worker.1]: State changed from up to starting
2021-02-20T18:55:10.493710+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2021-02-20T18:55:10.820252+00:00 heroku[worker.1]: Process exited with status 0
2021-02-20T18:55:14.968882+00:00 heroku[worker.1]: Starting process with command `python bot/main.py`
2021-02-20T18:55:15.742171+00:00 heroku[worker.1]: State changed from starting to up
2021-02-20T18:55:18.399511+00:00 app[worker.1]: prod
2021-02-20T18:55:21.252081+00:00 app[worker.1]: expected create exception: constraint "usr_fk0" for relation "usr" already exists
2021-02-21T19:26:29.609958+00:00 heroku[worker.1]: Cycling
2021-02-21T19:26:29.637337+00:00 heroku[worker.1]: State changed from up to starting
2021-02-21T19:26:30.895332+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2021-02-21T19:26:31.206732+00:00 heroku[worker.1]: Process exited with status 0
2021-02-21T19:26:34.256366+00:00 heroku[worker.1]: Starting process with command `python bot/main.py`
2021-02-21T19:26:34.879461+00:00 heroku[worker.1]: State changed from starting to up
2021-02-21T19:26:37.603928+00:00 app[worker.1]: prod
2021-02-21T19:26:41.546483+00:00 app[worker.1]: expected create exception: constraint "usr_fk0" for relation "usr" already exists
2021-02-22T18:54:38.000000+00:00 app[api]: Build started by user thederevin@gmail.com
2021-02-22T18:55:13.046840+00:00 app[api]: Deploy fba85ece by user thederevin@gmail.com
2021-02-22T18:55:13.046840+00:00 app[api]: Release v261 created by user thederevin@gmail.com
2021-02-22T18:55:14.787276+00:00 heroku[worker.1]: Restarting
2021-02-22T18:55:14.793446+00:00 heroku[worker.1]: State changed from up to starting
2021-02-22T18:55:16.246382+00:00 heroku[worker.1]: Stopping all processes with SIGTERM
2021-02-22T18:55:16.864884+00:00 heroku[worker.1]: Process exited with status 0
2021-02-22T18:55:19.338952+00:00 heroku[worker.1]: Starting process with command `python bot/main.py`
2021-02-22T18:55:20.085135+00:00 heroku[worker.1]: State changed from starting to up
2021-02-22T18:55:22.415751+00:00 app[worker.1]: prod
2021-02-22T18:55:23.757044+00:00 app[worker.1]: Traceback (most recent call last):
2021-02-22T18:55:23.757121+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 606, in _load_from_module_spec
2021-02-22T18:55:23.757499+00:00 app[worker.1]: spec.loader.exec_module(lib)
2021-02-22T18:55:23.757504+00:00 app[worker.1]: File "<frozen importlib._bootstrap_external>", line 678, in exec_module
2021-02-22T18:55:23.757644+00:00 app[worker.1]: File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2021-02-22T18:55:23.757763+00:00 app[worker.1]: File "/app/bot/cogs/message_handler.py", line 6, in <module>
2021-02-22T18:55:23.757894+00:00 app[worker.1]: from utils.regex import regex_handler
2021-02-22T18:55:23.757896+00:00 app[worker.1]: File "/app/bot/utils/regex.py", line 8, in <module>
2021-02-22T18:55:23.758027+00:00 app[worker.1]: from utils.reputation import regex_reputation_command
2021-02-22T18:55:23.758050+00:00 app[worker.1]: File "/app/bot/utils/reputation.py", line 15
2021-02-22T18:55:23.758077+00:00 app[worker.1]: if message.author.id == x.id:
2021-02-22T18:55:23.758120+00:00 app[worker.1]: ^
2021-02-22T18:55:23.758156+00:00 app[worker.1]: SyntaxError: invalid syntax
2021-02-22T18:55:23.758156+00:00 app[worker.1]: 
2021-02-22T18:55:23.758156+00:00 app[worker.1]: The above exception was the direct cause of the following exception:
2021-02-22T18:55:23.758157+00:00 app[worker.1]: 
2021-02-22T18:55:23.758159+00:00 app[worker.1]: Traceback (most recent call last):
2021-02-22T18:55:23.758159+00:00 app[worker.1]: File "bot/main.py", line 22, in <module>
2021-02-22T18:55:23.758324+00:00 app[worker.1]: bot.load_extension(f"cogs.{filename[:-3]}")
2021-02-22T18:55:23.758324+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 663, in load_extension
2021-02-22T18:55:23.758703+00:00 app[worker.1]: self._load_from_module_spec(spec, name)
2021-02-22T18:55:23.758704+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 609, in _load_from_module_spec
2021-02-22T18:55:23.759095+00:00 app[worker.1]: raise errors.ExtensionFailed(key, e) from e
2021-02-22T18:55:23.759118+00:00 app[worker.1]: discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.message_handler' raised an error: SyntaxError: invalid syntax (reputation.py, line 15)
2021-02-22T18:55:23.871884+00:00 heroku[worker.1]: Process exited with status 1
2021-02-22T18:55:23.926918+00:00 heroku[worker.1]: State changed from up to crashed
2021-02-22T18:55:23.937865+00:00 heroku[worker.1]: State changed from crashed to starting
2021-02-22T18:55:26.000000+00:00 app[api]: Build succeeded
2021-02-22T18:55:30.294840+00:00 heroku[worker.1]: Starting process with command `python bot/main.py`
2021-02-22T18:55:31.027526+00:00 heroku[worker.1]: State changed from starting to up
2021-02-22T18:55:34.125283+00:00 app[worker.1]: prod
2021-02-22T18:55:36.507099+00:00 app[worker.1]: Traceback (most recent call last):
2021-02-22T18:55:36.507120+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 606, in _load_from_module_spec
2021-02-22T18:55:36.507771+00:00 app[worker.1]: spec.loader.exec_module(lib)
2021-02-22T18:55:36.507809+00:00 app[worker.1]: File "<frozen importlib._bootstrap_external>", line 678, in exec_module
2021-02-22T18:55:36.508242+00:00 app[worker.1]: File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
2021-02-22T18:55:36.508472+00:00 app[worker.1]: File "/app/bot/cogs/message_handler.py", line 6, in <module>
2021-02-22T18:55:36.508680+00:00 app[worker.1]: from utils.regex import regex_handler
2021-02-22T18:55:36.508744+00:00 app[worker.1]: File "/app/bot/utils/regex.py", line 8, in <module>
2021-02-22T18:55:36.508948+00:00 app[worker.1]: from utils.reputation import regex_reputation_command
2021-02-22T18:55:36.508991+00:00 app[worker.1]: File "/app/bot/utils/reputation.py", line 15
2021-02-22T18:55:36.509020+00:00 app[worker.1]: if message.author.id == x.id:
2021-02-22T18:55:36.509101+00:00 app[worker.1]: ^
2021-02-22T18:55:36.509136+00:00 app[worker.1]: SyntaxError: invalid syntax
2021-02-22T18:55:36.509163+00:00 app[worker.1]: 
2021-02-22T18:55:36.509164+00:00 app[worker.1]: The above exception was the direct cause of the following exception:
2021-02-22T18:55:36.509164+00:00 app[worker.1]: 
2021-02-22T18:55:36.509193+00:00 app[worker.1]: Traceback (most recent call last):
2021-02-22T18:55:36.509256+00:00 app[worker.1]: File "bot/main.py", line 22, in <module>
2021-02-22T18:55:36.509465+00:00 app[worker.1]: bot.load_extension(f"cogs.{filename[:-3]}")
2021-02-22T18:55:36.509499+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 663, in load_extension
2021-02-22T18:55:36.510152+00:00 app[worker.1]: self._load_from_module_spec(spec, name)
2021-02-22T18:55:36.510755+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 609, in _load_from_module_spec
2021-02-22T18:55:36.511396+00:00 app[worker.1]: raise errors.ExtensionFailed(key, e) from e
2021-02-22T18:55:36.514364+00:00 app[worker.1]: discord.ext.commands.errors.ExtensionFailed: Extension 'cogs.message_handler' raised an error: SyntaxError: invalid syntax (reputation.py, line 15)
2021-02-22T18:55:36.770674+00:00 heroku[worker.1]: Process exited with status 1
2021-02-22T18:55:36.845804+00:00 heroku[worker.1]: State changed from up to crashed
2021-02-22T19:32:31.000000+00:00 app[api]: Build started by user thederevin@gmail.com
2021-02-22T19:33:04.007532+00:00 app[api]: Release v262 created by user thederevin@gmail.com
2021-02-22T19:33:04.007532+00:00 app[api]: Deploy f75147a0 by user thederevin@gmail.com
2021-02-22T19:33:05.202135+00:00 heroku[worker.1]: State changed from crashed to starting
2021-02-22T19:33:11.218769+00:00 heroku[worker.1]: Starting process with command `python bot/main.py`
2021-02-22T19:33:12.113215+00:00 heroku[worker.1]: State changed from starting to up
2021-02-22T19:33:14.701107+00:00 app[worker.1]: prod
2021-02-22T19:33:17.550791+00:00 app[worker.1]: expected create exception: constraint "usr_fk0" for relation "usr" already exists
2021-02-22T19:33:18.000000+00:00 app[api]: Build succeeded
2021-02-22T19:36:23.057494+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:36:23.057522+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:36:23.057522+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:36:23.068237+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:36:23.071633+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:36:23.283795+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:36:27.573104+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:36:27.573245+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:36:27.573281+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:36:27.576168+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:36:27.580016+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:36:27.994265+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:36:52.624504+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:36:52.624603+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:36:52.624641+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:36:52.627759+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:36:52.631060+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:36:52.861005+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:37:16.797066+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:37:16.797127+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:37:16.797163+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:37:16.799947+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:37:16.803838+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:37:17.035470+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:37:25.558785+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:37:25.558803+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:37:25.558804+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:37:25.561495+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:37:25.567267+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:37:25.778255+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:37:33.637699+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:37:33.637782+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:37:33.637816+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:37:33.640969+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:37:33.647346+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:37:33.907964+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:37:38.765530+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:37:38.765646+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:37:38.765650+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:37:38.768500+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:37:38.772044+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:37:39.045607+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:37:43.257954+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:37:43.257973+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:37:43.257974+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:37:43.261832+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:37:43.265360+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:37:43.518262+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:37:55.535192+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:37:55.535222+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:37:55.535223+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:37:55.539633+00:00 app[worker.1]: Adding user 255175001802670080 with guild 315247766739615745 to db.
2021-02-22T19:37:55.544979+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:37:55.548307+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:37:55.755852+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:38:02.628215+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:38:02.628297+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:38:02.628334+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:38:02.631309+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:38:02.634723+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:38:02.913273+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:38:05.307361+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:38:05.307432+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:38:05.307468+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:38:05.316339+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:38:05.322285+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:38:05.595649+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:38:19.388050+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:38:19.388174+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:38:19.388208+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:38:19.395801+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:38:19.400637+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:38:19.624524+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:38:25.155475+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:38:25.155625+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:38:25.155662+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:38:25.158646+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:38:25.163265+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:38:25.520720+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:38:42.668308+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:38:42.668318+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:38:42.668319+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:38:42.672102+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:38:42.680410+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:38:42.930894+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:38:51.521908+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:38:51.521952+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:38:51.521952+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:38:51.524665+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:38:51.528085+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:38:51.767331+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:38:54.243605+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:38:54.243639+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:38:54.243640+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:38:54.246579+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:38:54.250154+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:38:54.513609+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:39:00.039445+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:39:00.039543+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:39:00.039576+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:39:00.043304+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:39:00.046572+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:39:00.273428+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:39:04.462327+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:39:04.462453+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:39:04.462516+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:39:04.465428+00:00 app[worker.1]: Adding user 334830848123600906 with guild 315247766739615745 to db.
2021-02-22T19:39:04.469104+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:39:04.472074+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:39:04.713200+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:39:16.862098+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:39:16.862118+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:39:16.862119+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:39:16.865052+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:39:16.872416+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:39:17.110826+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:39:23.957345+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:39:23.957615+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:39:23.957616+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:39:23.961870+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:39:23.968712+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:39:24.174720+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:39:33.721374+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:39:33.721436+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:39:33.721469+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:39:33.727555+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:39:33.737089+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:39:34.037610+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:40:26.566122+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:40:26.566137+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:40:26.566138+00:00 app[worker.1]: debug: message is a self-thank
2021-02-22T19:40:26.789601+00:00 app[worker.1]: debug: self-thank message sent
2021-02-22T19:40:31.457444+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:40:31.458407+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:40:31.458442+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:40:31.464363+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:40:31.468681+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:40:31.697468+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:40:38.878485+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:40:38.878754+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:40:38.878791+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:40:38.882005+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:40:38.887421+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:40:39.152131+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:40:40.121377+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:40:40.121559+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:40:40.121605+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:40:40.124442+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:40:40.127892+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:40:40.344590+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:40:49.833527+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:40:49.833544+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:40:49.833545+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:40:49.844508+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:40:49.855497+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:40:50.075358+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:40:50.234057+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:40:50.234151+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:40:50.234190+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:40:50.237529+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:40:50.243386+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:40:50.556495+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:41:07.814685+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:41:07.814699+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:41:07.814700+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:41:07.820588+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:41:07.824726+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:41:08.183695+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:41:13.700318+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:41:13.700390+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:41:13.700419+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:41:13.703582+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:41:13.707742+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:41:13.973501+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:41:46.439624+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:41:46.439758+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:41:46.439797+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:41:46.462844+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:41:46.472430+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:41:46.688702+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:42:09.303496+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:42:09.303518+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:42:09.303519+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:42:09.306213+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:42:09.309358+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:42:09.534851+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:42:16.355669+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:42:16.355696+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:42:16.355697+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:42:16.360220+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:42:16.366183+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:42:16.597589+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:42:22.608278+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:42:22.608296+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:42:22.608297+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:42:22.612436+00:00 app[worker.1]: Adding user 159985870458322944 with guild 315247766739615745 to db.
2021-02-22T19:42:22.616607+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:42:22.620583+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:42:22.817052+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:42:32.366479+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:42:32.366583+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:42:32.366616+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:42:32.369503+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:42:32.373321+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:42:32.610602+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:42:47.388722+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:42:47.388826+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:42:47.388830+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:42:47.393055+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:42:47.399088+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:42:47.662313+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:42:57.114074+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:42:57.114178+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:42:57.114219+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:42:57.119762+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:42:57.130583+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:42:57.441022+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:43:00.096352+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:43:00.096498+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:43:00.096536+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:43:00.099487+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:43:00.103691+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:43:00.340785+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:43:19.612329+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:43:19.612388+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:43:19.612389+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:43:19.620588+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:43:19.628014+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:43:19.920712+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:43:40.029491+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:43:40.029592+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:43:40.029629+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:43:40.037767+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:43:40.044353+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:43:40.323648+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:43:56.493810+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:43:56.499006+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:43:56.499051+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:43:56.504720+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:43:56.508486+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:43:56.774794+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:44:00.330619+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:44:00.330633+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:44:00.330633+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:44:00.337617+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:44:00.341605+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:44:00.547296+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:44:02.465118+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:44:02.465212+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:44:02.465249+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:44:02.468396+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:44:02.472897+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:44:02.686185+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:44:14.419275+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:44:14.419372+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:44:14.419412+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:44:14.428223+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:44:14.434562+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:44:14.639583+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:44:23.329810+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:44:23.329984+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:44:23.330039+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:44:23.333204+00:00 app[worker.1]: Adding user 242350711696785420 with guild 315247766739615745 to db.
2021-02-22T19:44:23.338660+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:44:23.342557+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:44:23.574404+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:44:27.882659+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:44:27.882733+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:44:27.882766+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:44:27.886828+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:44:27.893441+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:44:28.172223+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:44:31.518954+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:44:31.518978+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:44:31.518978+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:44:31.521783+00:00 app[worker.1]: Adding user 267829682110595072 with guild 315247766739615745 to db.
2021-02-22T19:44:31.525418+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:44:31.532362+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:44:31.793652+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:44:43.162556+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:44:43.162643+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:44:43.162679+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:44:43.174206+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:44:43.178887+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:44:43.505899+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:44:49.825827+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:44:49.825907+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:44:49.825944+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:44:49.829630+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:44:49.833130+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:44:50.153836+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:45:05.941498+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:45:05.942070+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:45:05.942110+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:45:05.945100+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:45:05.948323+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:45:06.194630+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:45:11.212157+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:45:11.212239+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:45:11.212277+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:45:11.215057+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:45:11.219184+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:45:11.468400+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:45:12.215787+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:45:12.215807+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:45:12.215866+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:45:12.218827+00:00 app[worker.1]: Adding user 242271100011020288 with guild 315247766739615745 to db.
2021-02-22T19:45:12.222573+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:45:12.225979+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:45:12.505508+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:45:15.709540+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:45:15.709583+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:45:15.709583+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:45:15.718450+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:45:15.724557+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:45:16.025502+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:45:19.622838+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:45:19.622853+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:45:19.622854+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:45:19.625931+00:00 app[worker.1]: Adding user 303871789967343616 with guild 315247766739615745 to db.
2021-02-22T19:45:19.630216+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:45:19.633376+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:45:19.920168+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:45:19.934692+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:45:19.935948+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:45:19.935990+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:45:19.957626+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:45:19.970685+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:45:20.208226+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:45:21.857581+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:45:21.857664+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:45:21.857700+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:45:21.868857+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:45:21.872325+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:45:22.190916+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:45:25.372374+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:45:25.372426+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:45:25.372469+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:45:25.375537+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:45:25.384470+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:45:25.645470+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:45:25.645543+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:45:25.645579+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:45:25.651588+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:45:25.656099+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:45:25.689618+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:45:25.994254+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:45:27.121992+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:45:27.122378+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:45:27.122435+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:45:27.126083+00:00 app[worker.1]: Adding user 283025369647546368 with guild 315247766739615745 to db.
2021-02-22T19:45:27.130096+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:45:27.133360+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:45:27.425660+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:45:32.121434+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:45:32.122431+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:45:32.122469+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:45:32.128356+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:45:32.139353+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:45:32.385491+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:45:36.746391+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:45:36.746473+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:45:36.746512+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:45:36.760551+00:00 app[worker.1]: Adding user 155785854231642112 with guild 315247766739615745 to db.
2021-02-22T19:45:36.774965+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:45:36.778529+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:45:37.002140+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:45:37.247241+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:45:37.247255+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:45:37.247255+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:45:37.250318+00:00 app[worker.1]: Adding user 216229098404446208 with guild 315247766739615745 to db.
2021-02-22T19:45:37.253821+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:45:37.257228+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:45:37.526446+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:45:38.360206+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:45:38.363038+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:45:38.363043+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:45:38.366308+00:00 app[worker.1]: Adding user 308645374761893890 with guild 315247766739615745 to db.
2021-02-22T19:45:38.370304+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:45:38.374787+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:45:38.709143+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:45:52.219434+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:45:52.219464+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:45:52.219465+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:45:52.222222+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:45:52.225623+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:45:52.530926+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:45:56.721740+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:45:56.721803+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:45:56.721840+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:45:56.724519+00:00 app[worker.1]: Adding user 185163274172628992 with guild 315247766739615745 to db.
2021-02-22T19:45:56.728509+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:45:56.731562+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:45:56.961483+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:46:02.138258+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:46:02.138286+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:46:02.138286+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:46:02.140907+00:00 app[worker.1]: Adding user 131986905624477697 with guild 315247766739615745 to db.
2021-02-22T19:46:02.144065+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:46:02.147309+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:46:02.388659+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:46:06.199761+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:46:06.200264+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:46:06.200311+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:46:06.204914+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:46:06.215764+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:46:06.491372+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:46:08.717467+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:46:08.717553+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:46:08.717589+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:46:08.722958+00:00 app[worker.1]: Adding user 408689123742711819 with guild 315247766739615745 to db.
2021-02-22T19:46:08.728381+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:46:08.733740+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:46:08.969688+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:46:10.341556+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:46:10.341646+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:46:10.341686+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:46:10.345646+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:46:10.351993+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:46:10.635311+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:46:29.176275+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:46:29.176346+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:46:29.176385+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:46:29.180009+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:46:29.183499+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:46:29.417895+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:46:48.888976+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:46:48.889243+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:46:48.889275+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:46:48.894356+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:46:48.898247+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:46:49.309830+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:46:54.628723+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:46:54.628741+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:46:54.628742+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:46:54.631489+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:46:54.635914+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:46:54.997140+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:47:04.069788+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:47:04.070057+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:47:04.070096+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:47:04.073139+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:47:04.076914+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:47:04.337471+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:47:09.374191+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:47:09.374200+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:47:09.374200+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:47:09.380137+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:47:09.387815+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:47:09.759246+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:47:12.934147+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:47:12.940338+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:47:12.940385+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:47:12.948499+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:47:12.954572+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:47:13.205576+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:47:22.260959+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:47:22.262315+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:47:22.262319+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:47:22.268393+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:47:22.271879+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:47:22.597534+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:47:22.894664+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:47:22.897468+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:47:22.900579+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:47:22.906182+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:47:22.909759+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:47:23.177391+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:47:23.452339+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:47:23.452352+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:47:23.452353+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:47:23.455655+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:47:23.459131+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:47:23.759652+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:47:36.657581+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:47:36.658118+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:47:36.658161+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:47:36.663865+00:00 app[worker.1]: Adding user 554326588557230100 with guild 315247766739615745 to db.
2021-02-22T19:47:36.671423+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:47:36.680412+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:47:36.909592+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:47:39.784557+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:47:39.784574+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:47:39.784575+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:47:39.792416+00:00 app[worker.1]: Adding user 352755021827407873 with guild 315247766739615745 to db.
2021-02-22T19:47:39.802704+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:47:39.806002+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:47:40.084324+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:47:47.225720+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:47:47.225988+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:47:47.226030+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:47:47.230385+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:47:47.234037+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:47:47.497290+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:47:49.436777+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:47:49.436889+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:47:49.436929+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:47:49.442150+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:47:49.449131+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:47:49.681278+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:47:53.780623+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:47:53.780680+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:47:53.780681+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:47:53.783382+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:47:53.786431+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:47:54.056640+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:47:54.427748+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:47:54.427767+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:47:54.427767+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:47:54.431226+00:00 app[worker.1]: Adding user 172370456098242560 with guild 315247766739615745 to db.
2021-02-22T19:47:54.434786+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:47:54.438519+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:47:54.673657+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:48:11.022328+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:48:11.022342+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:48:11.022342+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:48:11.025409+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:48:11.028745+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:48:11.082306+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:48:11.082312+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:48:11.082313+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:48:11.085798+00:00 app[worker.1]: Adding user 121305317278482433 with guild 315247766739615745 to db.
2021-02-22T19:48:11.089268+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:48:11.092743+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:48:11.386886+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:48:11.633677+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:48:12.125533+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:48:12.125570+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:48:12.125570+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:48:12.128535+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:48:12.132097+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:48:12.426125+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:48:25.209378+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:48:25.209396+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:48:25.209397+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:48:25.214453+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:48:25.219479+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:48:25.493469+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:48:29.109447+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:48:29.109515+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:48:29.109552+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:48:29.113284+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:48:29.120406+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:48:29.377147+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:48:31.040076+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:48:31.040089+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:48:31.040203+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:48:31.043888+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:48:31.047627+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:48:31.283682+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:48:32.145727+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:48:32.152164+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:48:32.152203+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:48:32.161089+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:48:32.170719+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:48:32.389270+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:48:32.512345+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:48:32.512426+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:48:32.512465+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:48:32.515906+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:48:32.519977+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:48:32.728841+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:48:33.155314+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:48:33.155328+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:48:33.155328+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:48:33.157922+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:48:33.161829+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:48:33.461319+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:48:33.461341+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:48:33.461341+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:48:33.464278+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:48:33.467619+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:48:33.542203+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:48:33.718280+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:48:33.718290+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:48:33.718314+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:48:33.724228+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:48:33.730831+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:48:33.890015+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:48:33.964021+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:48:33.964574+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:48:33.964629+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:48:33.968755+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:48:33.974958+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:48:34.219510+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:48:34.219527+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:48:34.219528+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:48:34.222239+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:48:34.225624+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:48:34.548035+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:48:34.548080+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:48:34.548081+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:48:34.551240+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:48:34.556560+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:48:34.889444+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:48:34.889498+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:48:34.889536+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:48:34.893403+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:48:34.897707+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:48:36.626084+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:48:36.872788+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:48:39.302966+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:48:39.302978+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:48:39.302978+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:48:39.305706+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:48:39.309648+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:48:39.673051+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:48:39.673068+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:48:39.673068+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:48:39.675363+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:48:39.678721+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:48:39.786846+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:48:39.997774+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:48:39.997788+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:48:39.997789+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:48:40.000508+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:48:40.004360+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:48:40.034324+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:48:40.250652+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:48:40.289485+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:48:40.289495+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:48:40.289496+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:48:40.292824+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:48:40.296374+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:48:40.585072+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:48:40.585259+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:48:40.585327+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:48:40.588933+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:48:40.592609+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:48:40.958289+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:48:40.958310+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:48:40.958356+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:48:40.961222+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:48:40.964725+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:48:41.861529+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:48:42.081548+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:48:42.352093+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:48:42.590962+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:48:42.818809+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:48:47.097595+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:48:52.577897+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:48:52.581028+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:48:52.581086+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:48:52.586126+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:48:52.597309+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:48:52.869612+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:49:28.383880+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:49:28.383901+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:49:28.383901+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:49:28.392370+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:49:28.395900+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:49:28.701845+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:49:35.295410+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:49:35.295451+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:49:35.295452+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:49:35.298467+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:49:35.302367+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:49:35.577874+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:49:52.897523+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:49:52.897554+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:49:52.897555+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:49:52.900753+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:49:52.904892+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:49:53.121242+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T19:50:12.475021+00:00 app[worker.1]: debug: message has thanks + mention
2021-02-22T19:50:12.475037+00:00 app[worker.1]: debug: starting for loop
2021-02-22T19:50:12.475038+00:00 app[worker.1]: debug: not a self-thank
2021-02-22T19:50:12.478994+00:00 app[worker.1]: debug: existence ensured
2021-02-22T19:50:12.484490+00:00 app[worker.1]: debug: DB command executed
2021-02-22T19:50:12.901988+00:00 app[worker.1]: debug: confirmation message sent
2021-02-22T20:15:11.970396+00:00 app[worker.1]: Unhandled exception in internal background task 'check_giveaways'.
2021-02-22T20:15:11.976352+00:00 app[worker.1]: Traceback (most recent call last):
2021-02-22T20:15:11.976405+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/discord/ext/tasks/__init__.py", line 101, in _loop
2021-02-22T20:15:11.976405+00:00 app[worker.1]: await self.coro(*args, **kwargs)
2021-02-22T20:15:11.976410+00:00 app[worker.1]: File "/app/bot/cogs/giveaways.py", line 226, in check_giveaways
2021-02-22T20:15:11.976411+00:00 app[worker.1]: async for message in giveaway_channel.history(limit=25):
2021-02-22T20:15:11.976411+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/discord/iterators.py", line 91, in __anext__
2021-02-22T20:15:11.976413+00:00 app[worker.1]: msg = await self.next()
2021-02-22T20:15:11.976415+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/discord/iterators.py", line 285, in next
2021-02-22T20:15:11.976416+00:00 app[worker.1]: await self.fill_messages()
2021-02-22T20:15:11.976443+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/discord/iterators.py", line 331, in fill_messages
2021-02-22T20:15:11.976443+00:00 app[worker.1]: data = await self._retrieve_messages(self.retrieve)
2021-02-22T20:15:11.976445+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/discord/iterators.py", line 351, in _retrieve_messages_before_strategy
2021-02-22T20:15:11.976445+00:00 app[worker.1]: data = await self.logs_from(self.channel.id, retrieve, before=before)
2021-02-22T20:15:11.976450+00:00 app[worker.1]: File "/app/.heroku/python/lib/python3.6/site-packages/discord/http.py", line 258, in request
2021-02-22T20:15:11.976451+00:00 app[worker.1]: raise DiscordServerError(r, data)
2021-02-22T20:15:11.976484+00:00 app[worker.1]: discord.errors.DiscordServerError: 500 Internal Server Error (error code: 0): 500: Internal Server Error
